name: Validate Infra + Scripts

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Bicep
        run: |
          az bicep version || echo "Bicep not available in runner"
          # Optionally run `bicep build` if bicep CLI available

      - name: Shellcheck scripts
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: error
          reporter: github-pr-review
          # runs shellcheck on scripts folder
          filter_mode: file
